<div id="<?php echo $this->getHtmlId() ?>">
<table cellspacing="0" cellpadding="0" class="massaction">
<tr>
    <td><?php if ($this->getUseSelectAll()):?>
            <a href="#" onclick="return <?php echo $this->getJsObjectName() ?>.selectAll()"><?php echo Mage::helper('aoe_gridSelectLinks')->__('All') ?></a>
            <span class="separator">|</span>
            <a href="#" onclick="return <?php echo $this->getJsObjectName() ?>.unselectAll()"><?php echo Mage::helper('aoe_gridSelectLinks')->__('None') ?></a>
            <span class="separator">|</span>
        <?php endif; ?>
        <?php if ($this->showAdditionalLinks()) : ?>
            <a href="#" onclick="return <?php echo $this->getJsObjectName() ?>.selectNotGreen()"><?php echo Mage::helper('aoe_gridSelectLinks')->__('Not Green') ?></a>
            <span class="separator">|</span>
            <a href="#" onclick="return <?php echo $this->getJsObjectName() ?>.unselectNotGreen()"><?php echo Mage::helper('aoe_gridSelectLinks')->__('Unselect Not Green') ?></a>
            <span class="separator">|</span>
        <?php endif; ?>
        <strong id="<?php echo $this->getHtmlId() ?>-count">0</strong> <?php echo $this->__('items selected') ?>
    </td>
    <td>
        <div class="right">
            <div class="entry-edit">
                <?php if ($this->getHideFormElement() !== true):?>
                <form action="" id="<?php echo $this->getHtmlId() ?>-form" method="post">
                <?php endif ?>
                    <?php echo $this->getBlockHtml('formkey')?>
                    <fieldset>
                        <span class="field-row">
                            <label><?php echo $this->__('Actions') ?></label>
                            <select id="<?php echo $this->getHtmlId() ?>-select" class="required-entry select absolute-advice local-validation">
                                <option value=""></option>
                                <?php foreach($this->getItems() as $_item): ?>
                                    <option value="<?php echo $_item->getId() ?>"<?php echo ($_item->getSelected() ? ' selected="selected"' : '')?>><?php echo $_item->getLabel() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </span>
                        <span class="outer-span" id="<?php echo $this->getHtmlId() ?>-form-hiddens"></span>
                        <span class="outer-span" id="<?php echo $this->getHtmlId() ?>-form-additional"></span>
                        <span class="field-row">
                            <?php echo $this->getApplyButtonHtml() ?>
                        </span>
                    </fieldset>
                <?php if ($this->getHideFormElement() !== true):?>
                </form>
                <?php endif ?>
            </div>

            <div class="no-display">
            <?php foreach($this->getItems() as $_item): ?>
                <div id="<?php echo $this->getHtmlId() ?>-item-<?php echo $_item->getId() ?>-block">
                    <?php echo $_item->getAdditionalActionBlockHtml() ?>
                </div>
            <?php endforeach; ?>
            </div>
        </div>
    </td>
</tr>
</table>
<?php if(!$this->getParentBlock()->canDisplayContainer()): ?>
<script type="text/javascript">
    <?php echo $this->getJsObjectName() ?>.setGridIds('<?php echo $this->getGridIdsJson() ?>');
</script>
<?php endif; ?>
</div>
<script type="text/javascript">
    Event.observe(window, "load", function(){
        <?php echo $this->getJsObjectName() ?>.selectNotGreen();
    });
</script>
